config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  root 'questions#index'

  resources 'users', only: [:index, :show]
  resources 'questions' do
    resources 'votes', only: [:create, :destroy]
    resources 'answers' do
      resources 'votes', only: [:create, :destroy]

    end
    resources 'favorites', only: [:create, :destroy]
  end

  resources 'tags', only: [:index, :show]

  get 'favorites/index'
  get 'ranking/index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :question, counter_cache: true
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def index
    @favorites = current_user.favorites.includes(:question)
  end

  def create
    @question = Question.find(params[:question_id])
    favorite = current_user.favorites.build(question_id: @question.id)
    unless favorite.save
      redirect_to questions_path
    end
  end

  def destroy
    favorite = Favorite.find(params[:id])
    @question = favorite.question
    unless favorite.destroy
      redirect_to questions_path
    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
  def is_favorite?(question)
    Favorite.find_by(user_id: current_user.id, question_id: question.id) != nil
  end
end

app/views/favorites/_favorite_button.html.erb
<% if user_signed_in? %>
  <% unless is_favorite?(question) %>
    <%= link_to question_favorites_path(question.id), method: :post, remote: true do %>
      <i class="fa fa-star-o fa-2x" aria-hidden="true"></i>
    <% end %>
  <% else %>
    <%= link_to question_favorite_path(question.id, question.favorite_by(current_user)), method: :delete, remote: true do %>
      <i class="favorited fa fa-star fa-2x" aria-hidden="true"></i>
    <% end %>
  <% end %>
<% else %>
  <%= link_to new_user_session_path do %>
    <i class="fa fa-star-o fa-2x" aria-hidden="true"></i>
  <% end %>
<% end %>

app/views/favorites/create.js.erb
$('.question-<%= @question.id %>-favorite-button').html("<%=j render partial: 'favorites/favorite_button' , locals: {question: @question} %>");

app/views/favorites/destroy.js.erb
$('.question-<%= @question.id %>-favorite-button').html("<%=j render partial: 'favorites/favorite_button' , locals: {question: @question} %>");

app/views/favorites/index.html.erb
<h1>お気に入り一覧</h1>
<% if is_blank?(@favorites) %>
  <%= "お気に入りは0件です" %><br>
<% end %>

<% @favorites.each do |favorite| %>
  <div class="row">
    <div class="col-md-2 col-sm-2">
      <%= render partial: "questions/additional_infomation", locals: {question: favorite.question} %>
    </div>
    <div class="col-md-10 col-sm-10">
      <p>
        <%= link_to question_path(favorite.question) do %><%= favorite.question.title %><% end %>
      </p>
      <ul class="list-inline">
        <li class="pull-left">
          <%= render partial: "tags/tag_list", locals: {tags: favorite.question.tags} %>
        </li>
        <li class="pull-right">
          更新日時 :<%= date_japan(favorite.question.updated_at) %>
          <%= link_to user_path(favorite.question.user) do %><%= favorite.question.user.name %><% end %>
        </li>
      </ul>
    </div>
    <div class="col-md-12 col-sm-12">
      <hr>
    </div>
  </div>
<% end %>