config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  root 'questions#index'

  resources 'users', only: [:index, :show]
  resources 'questions' do
    resources 'votes', only: [:create, :destroy]
    resources 'answers' do
      resources 'votes', only: [:create, :destroy]

    end
    resources 'favorites', only: [:create, :destroy]
  end

  resources 'tags', only: [:index, :show]

  get 'favorites/index'
  get 'ranking/index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings, dependent: :destroy
  has_many :questions, through: :taggings

  def self.register!(name)
    tag = Tag.find_by(name: name)
    #存在しなかったら新規登録
    if is_not_registered?(tag)
      tag = Tag.create!(name: name)
    end
    tag
  end


  private
  def self.is_not_registered?(tag)
    tag.nil?
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
    @tags = @tag.questions.includes(:user, :tags)
  end
end

app/helpers/tags_helper.rb
module TagsHelper
  def comma_join(tags)
    result = []
    tags.each do |tag|
      result << tag[:name]
    end
    result.join(",")
  end
end

app/views/tags/_tag_index.html.erb
<% tags.each do |tag| %>
  <div class="col-md-3 col-sm-3">
    <div class="tag-box">
      <P><%= link_to tag_path(tag), class: "tag" do %><%= tag.name %><% end %></p>
      <p>関連質問数: <%= tag.taggings.count %></p>
    </div>
  </div>
<% end %>

app/views/tags/_tag_list.html.erb
<% tags.each do |tag| %>
  <%= link_to tag_path(tag), class: "tag" do %><%= tag.name %><% end %>
<% end %>

app/views/tags/index.html.erb
<h1>タグ一覧</h1>

<div class="row">
  <%= render partial: "tags/tag_index", locals: {tags: @tags} %>
</div>

app/views/tags/show.html.erb
<h1>タグ付けされた質問</h1>
<div id="tag_space">
  <span class="tag" ><%= @tag.name %></span>
</div>

<% @tags.each_with_index do |tag, i| %>
  <div class="row">
    <div class="col-md-2 col-sm-2">
      <%= render partial: "questions/additional_infomation", locals: {question: tag} %>
    </div>
    <div class="col-md-10 col-sm-10">
      <p>
        <%= link_to question_path(tag) do %><%= tag.title %><% end %>
      </p>
      <ul class="list-inline">
        <li class="pull-left">
          <%= render partial: "tags/tag_list", locals: {tags: tag.tags} %>
        </li>
        <li class="pull-right">
          更新日時 :<%= date_japan(tag.updated_at) %>
          <%= link_to user_path(tag.user) do %><%= tag.user.name %><% end %>
        </li>
      </ul>
    </div>
    <div class="col-md-12 col-sm-12">
      <hr>
    </div>
  </div>
<% end %>