config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  root 'questions#index'

  resources 'users', only: [:index, :show]
  resources 'questions' do
    resources 'votes', only: [:create, :destroy]
    resources 'answers' do
      resources 'votes', only: [:create, :destroy]

    end
    resources 'favorites', only: [:create, :destroy]
  end

  resources 'tags', only: [:index, :show]

  get 'favorites/index'
  get 'ranking/index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :answer
  belongs_to :question
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
#長くなりすぎなのでリファクタリングしたい
  respond_to :js
  def create
    if params[:question_or_answer] == "question"
      @question = Question.find(params[:question_id])
      if current_user.question_voting_plus_or_minus_or_nil(@question)
        @vote = Vote.find(params[:id])
        @vote.destroy
        respond_with @question, template: 'votes/vote_question'
      else
        @question = Question.find(params[:question_id])
        if params[:is_up] == "true"
          plus_or_minus = 1
        else
          plus_or_minus = -1
        end
        Vote.create(user_id: current_user.id, question_id: @question.id, plus_or_minus: plus_or_minus)
        respond_with @question, template: 'votes/vote_question'
      end
    else #params[:question_or_answer] !== "question"
      @answer = Answer.find(params[:answer_id])
      @question = @answer.question
      if current_user.answer_voting_plus_or_minus_or_nil(@answer)
        @vote = Vote.find(params[:id])
        @vote.destroy
        respond_with @answer, template: 'votes/vote_answer'
      else
        @answer = Answer.find(params[:answer_id])
        if params[:is_up] == "true"
          plus_or_minus = 1
        else
          plus_or_minus = -1
        end
        Vote.create(user_id: current_user.id, answer_id: @answer.id, plus_or_minus: plus_or_minus)
        respond_with @answer, template: 'votes/vote_answer'
      end
    end
  end

  def destroy
    if params[:question_or_answer] == "question"
      @question = Question.find(params[:question_id])
      if current_user.question_voting_plus_or_minus_or_nil(@question)
        @vote = Vote.find(params[:id])
        @vote.destroy
        respond_with @question, template: 'votes/vote_question'
      else
        @question = Question.find(params[:question_id])
        plus_or_minus = -1
        Vote.create(user_id: current_user.id, question_id: @question.id, plus_or_minus: plus_or_minus)
        respond_with @question, template: 'votes/vote_question'
      end
    else #params[:question_or_answer] !== "question"
      @answer = Answer.find(params[:answer_id])
      @question = @answer.question
      if current_user.answer_voting_plus_or_minus_or_nil(@answer)
        @vote = Vote.find(params[:id])
        @vote.destroy
        respond_with @answer, template: 'votes/vote_answer'
      else
        @answer = Answer.find(params[:answer_id])
        plus_or_minus = -1
        Vote.create(user_id: current_user.id, answer_id: @answer.id, plus_or_minus: plus_or_minus)
        respond_with @answer, template: 'votes/vote_answer'
      end
    end
  end
end

app/views/votes/_vote_answer.html.erb
<div>
  <% if current_user %>
    <% if current_user.answer_voting_plus_or_minus_or_nil(answer) == 1 %>
      <div class="fa fa-caret-up fa-3x fa-cannot-vote"></div>
      <div class="vote-point"><%= answer.voted_point %></div>
      <%= link_to question_answer_vote_path(answer.question,answer,answer.votes.find_by(user_id: current_user.id)), method: :delete, remote: true do %>
        <div class="fa fa-caret-down fa-3x fa-can-vote"></div>
      <% end %>
    <% elsif current_user.answer_voting_plus_or_minus_or_nil(answer) == -1 %>
    <%= link_to question_answer_vote_path(answer.question,answer,answer.votes.find_by(user_id: current_user.id)), method: :delete, remote: true do %>
        <div class="fa fa-caret-up fa-3x fa-can-vote"></div>
      <% end %>
      <div class="vote-point"><%= answer.voted_point %></div>
      <div class="fa fa-caret-down fa-3x fa-cannot-vote"></div>
    <% else %>
      <%= link_to question_answer_votes_path(answer.question,answer, params: {is_up: true}), method: :post, remote: true do %>
        <div class="fa fa-caret-up fa-3x fa-can-vote"></div>
      <% end %>
      <div class="vote-point"><%= answer.voted_point %></div>
      <%= link_to question_answer_votes_path(answer.question,answer, params: {is_up: false}), method: :post, remote: true do %>
        <div class="fa fa-caret-down fa-3x fa-can-vote"></div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/votes/_vote_question.html.erb
<div>
  <% if current_user %>
    <% if current_user.question_voting_plus_or_minus_or_nil(@question) == 1 %>
      <div class="fa fa-caret-up fa-3x fa-cannot-vote"></div>
      <div class="vote-point"><%= @question.voted_point %></div>
      <%= link_to question_vote_path(@question,@question.votes.find_by(user_id: current_user.id), params: {question_or_answer: "question"}), method: :delete, remote: true do %>
        <div class ="fa fa-caret-down fa-3x fa-can-vote"></div>
      <% end %>
    <% elsif current_user.question_voting_plus_or_minus_or_nil(@question) == -1 %>
    <%= link_to question_vote_path(@question,@question.votes.find_by(user_id: current_user.id), params: {question_or_answer: "question"}), method: :delete, remote: true do %>
        <div class="fa fa-caret-up fa-3x fa-can-vote"></div>
      <% end %>
      <div class="vote-point"><%= @question.voted_point %></div>
      <div class="fa fa-caret-down fa-3x fa-cannot-vote"></div>
    <% else %>
      <%= link_to question_votes_path(@question, params: {is_up: true, question_or_answer: "question"}), method: :post, remote: true do %>
        <div class="fa fa-caret-up fa-3x fa-can-vote"></div>
      <% end %>
      <div class="vote-point"><%= @question.voted_point %></div>
      <%= link_to question_votes_path(@question, params: {is_up: false, question_or_answer: "question"}), method: :post, remote: true do %>
        <div class="fa fa-caret-down fa-3x fa-can-vote"></div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/votes/vote_answer.js.erb
$("#vote-answer").html("<%= j(render 'votes/vote_answer', { answer: @answer }) %>")

app/views/votes/vote_question.js.erb
$("#vote-question").html("<%= j(render 'votes/vote_question') %>")