config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  root 'questions#index'

  resources 'users', only: [:index, :show]
  resources 'questions' do
    resources 'votes', only: [:create, :destroy]
    resources 'answers' do
      resources 'votes', only: [:create, :destroy]

    end
    resources 'favorites', only: [:create, :destroy]
  end

  resources 'tags', only: [:index, :show]

  get 'favorites/index'
  get 'ranking/index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dive-23-10</title>
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#sp-nav" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "stack overflow Dive-23-10", root_path, class: "navbar-brand" %>
        </div>
        <div class="collapse navbar-collapse" id="sp-nav">
          <ul class="nav navbar-nav navbar-left">
            <li><%= link_to "質問一覧", root_path %></li>
            <li><%= link_to 'ランキング', ranking_index_path %></li>
            <li><%= link_to 'ユーザー', users_path %></li>
            <li><%= link_to 'タグ', tags_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="img-profile-wrap-xs-original"><%= profile_img(current_user) %></span>
                <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'マイページ', user_path(current_user) %></li>
                  <li><%= link_to 'お気に入り', favorites_index_path %></li>
                  <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
              <li><%= link_to "＋質問する", new_question_path %></li>
            <% else %>
              <li><%= link_to 'ログイン', new_user_session_path  %></li>
              <li><%= link_to 'サインアップ', new_user_registration_path %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
  </header>

  <div class="yield container">
    <%= render partial: 'application/display_flash_message', flash: flash %>
    <%= yield %>
  <!-- /.container --></div>

  <footer>
    <p>© 2017 Copyright Dive-23-10</p>
  </footer>
  <%= javascript_include_tag 'application' %>
</body>
</html>